### ISSUE TITLE
Dropdown menus are rendered too small

### ISSUE THREAD

**Issue by sophimoo** [adriankarlen/textfox#45]
Expected behavior:

<img width="436" alt="Screenshot 2024-11-10 at 17 03 18" src="https://github.com/user-attachments/assets/ed4c9f33-6df8-4cab-9183-b8c5c4a4e7a6">

What happens in textfox, the window ends up smaller with a horizontal scroll within it

<img width="362" alt="Screenshot 2024-11-10 at 17 02 11" src="https://github.com/user-attachments/assets/87260304-1e8d-4223-945d-87a7d0b919a0">

No idea what the reason is 🤷‍♀️ may not be related to textfox but it doesn't happen on other firefox instances

**Comment by adriankarlen** [comment]
I think this has to do with the `variables.css` being imported in `userContent.css`. 

It has a variable `--font-size` which might be a bit too general.
Feels like it might be good to preface my variables with `tf-` to avoid clashing. Might be a good idea to separate the overrides too so that they are not used in `userContent.css`. Will investigate further while at my computer later on.
