### ISSUE TITLE
Firefox appearance not changing despite following install guide

### ISSUE THREAD

**Issue by Jean-Alessandro** [adriankarlen/textfox#6]
I'm new to using CSS and general theming like this, so guaranteed I'm just doing something wrong, but I've followed the steps listed on the installation section with no changes to my firefox appearance. I'm on trying to do this on windows if that changes things. 

I'm also a little confused as to what extort means in the guide, does this mean _extract_ the folder into chrome or just place it there.

**Comment by Bali10050** [comment]
@adriankarlen should look into making the install a bit more easy to understand, because it's really all over the place. I didn't install the sideberry part, but that should be the easiest, you just need to import some settings. Here's the easiest way to install in my opinion:

https://github.com/user-attachments/assets/9ff356bd-5973-4cd3-bbba-f39822c12847

**Comment by adriankarlen** [comment]
Yeah I agree that the installation is _**VERY**_ incomplete. I did not expect this to blow up the way it did and assumed it would only be used people already experienced in editing firefox css.

Will try to get a more proper documentation added ASAP. Will also look in to actually having releases with a zip containing the files in correct structure.

Thank you @Bali10050 for helping out with clarifying the instructions.

**Comment by Bali10050** [comment]
I recommend you to just have a file stucture like me: <https://github.com/Bali10050/FirefoxCSS>, then you don't have to worry about managing releases, and it looks less overwhelming for the people visiting your github
